version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource

  clickhouse:
    image: yandex/clickhouse-server
    container_name: clickhouse
    restart: always
    ports:
      - '8123:8123'
      - '9000:9000'
      - '9009:9009'
    volumes:
      - clickhouse_data:/var/lib/clickhouse

volumes:
  grafana_data:
  clickhouse_data:
